### ISSUE TITLE
gnome桌面下载的时候建议加一下怎么解压

### ISSUE THREAD

**Issue by bztMinamoto** [ustclug/Linux101-docs#18]
我解压的时候完全不知道按ctrl+H可以查看隐藏文件夹……还是去群里问了一下，不然建好了都不知道.themes在哪儿

**Comment by taoky** [comment]
尝试在 https://github.com/ustclug/Linux101-docs/commit/97ed2f68ccf2c9a1eb1c09b529d8b36804d5e842 加了一个 tip 解释这里出现的 `~` 以及隐藏文件的问题。
