### ISSUE TITLE
Ch01 虚拟机更新

### ISSUE THREAD

**Issue by taoky** [ustclug/Linux101-docs#21]
- Ubuntu 18.04 五年的支持即将结束
- Ubuntu 20.04 中需要关闭 LTS 大版本更新（有反馈点了更新之后系统挂了）
- 制作 Ubuntu 22.04 镜像
- 是否可以将 VMware 和 VirtualBox 的镜像合并为一个？

**Comment by iBug** [comment]
1. 准备撤下 Ubuntu 18.04 的镜像
2. *No response*
3. 制作镜像的过程是否可以像 [liimstrap](https://github.com/ustclug/liimstrap) 一样自动化，方便维护及制作出内容更加确定的镜像（即闭门造车）
4. 可以，之前的主要考虑是容量和兼容性问题。

   容量：VB 的镜像会比 VMware 的大 15% 左右（不少内容需要编译 + DKMS 等，不像 VMware 的 tools 是开箱即用的）。

   兼容性：不知道同一个虚拟机里装上 open-vm-tools 和 VB 的 Guest Additions 会不会冲突，尤其是后者有不少 kernel modules。
