### ISSUE TITLE
第三章有typo

### ISSUE THREAD

**Issue by junjie1475** [ustclug/Linux101-docs#23]
![image](https://user-images.githubusercontent.com/86281724/209664668-25058955-a00a-47e3-9e0a-2e67807812db.jpeg)

如图所示，`文件目录到`应该改为`文件拷贝到`

**Comment by taoky** [comment]
Fixed in https://github.com/ustclug/Linux101-docs/commit/094f03a2265d089fbdddefd6d5ce7b367a70ea8a
