### ISSUE TITLE
附录中关于 SELinux 的活动录像链接无访问权限

### ISSUE THREAD

**Issue by knowledgebee** [ustclug/Linux101-docs#25]
附录中关于 SELInux 的小节中有一段：

“ [清华大学 TUNA 协会](https://tuna.moe)曾在活动中做过 [SELinux 的使用介绍](https://tuna.moe/event/2020/selinux-introduction/)，希望进一步了解 SELinux 的同学可以在线观看其[活动录像](https://cloud.tsinghua.edu.cn/f/55d0ee97fce44c078982/)。”

但 “ [活动录像](https://cloud.tsinghua.edu.cn/f/55d0ee97fce44c078982/) ” 无访问权限
<img width="960" alt="image" src="https://user-images.githubusercontent.com/76278496/210584735-4111fa62-aa61-4ed1-9a92-40e9694c2b84.png">

**Comment by iBug** [comment]
我联系了 TUNA 的同学，对面建议用 <https://mirrors.tuna.tsinghua.edu.cn/tuna/tunight/2020-06-27-selinux-introduction/> 替代，已在 f959fd9cef80151bc39bb39e898df3fbdffae320 中修复。
