### ISSUE TITLE
对文档的一个建议

### ISSUE THREAD

**Issue by LeisureLinux** [ustclug/Linux101-docs#28]
我是 B站上 [LeisureLinux](https://space.bilibili.com/517298151) Up主，平常对文档的编写也比较关心，自己也想着写一本 **《Systemd 101》** 的书。我的粉丝中也有很多大学生或者毕业不久的同学。 感觉很多人还是对于使用网络资源有很大的障碍，国内高校的各种镜像其实是解决这个障碍的重要跳板。 

建议：**《Linux 101》** 的图书编写中，结合科大镜像站内的源，介绍源的使用。例如：
  - 介绍 pip 时，顺便介绍如何集成科大的 PyPi 镜像站。
  - 介绍 Debian 时，可以介绍在 sources.list 文件中，源的 URL 可以修改成 http://ftp.cn.debian.org/debian 这对于很多没有科学上网环境，甚至有科学上网环境的人也是有用的。毕竟很多科学上网也是有流量限制的。

**Comment by taoky** [comment]
1. 我们目前没有 PyPI 的镜像。
2. 文档里没有介绍 Debian 的换源操作，即使有这样做也可能不太合适。由于备案的问题，cn.archive.ubuntu.com 和 ftp.cn.debian.org 都无法解析到中国大陆境内，这会导致每下载一个包都会有一趟额外的 RTT（网络流量会先到非大陆的服务器一趟，然后返回 302 后再访问境内的镜像站）。
    - 如果是希望在 appendix/distribution 里面加的话，目前附录里的这一部分只做了很简单的介绍，并且重点是介绍各个发行版的特性，而非如何具体去使用。

**Comment by iBug** [comment]
注：`cn.archive.ubuntu.com` 不会 302，而是直接 200 提供文件
