### ISSUE TITLE
添加 Apple Silicon (ARM) 下的环境配置补充说明

### ISSUE THREAD

**Issue by taoky** [ustclug/Linux101-docs#29]
相关邮件咨询：

> 请问mac m1版本如何配置linux虚拟机呢？教程中的方法似乎并不能用

可以在第一章「拓展阅读」里面加入相关的内容（对 x86_64 和 ARM64 两种体系结构的简单解说、使用 UTM 或者 VMware Fusion 之类的软件安装 ARM64 架构的 Ubuntu 的说明、以及能否用 UTM 直接跑 x86_64 架构的带桌面环境的 Linux？至于虚拟机预配置的镜像我感觉可以暂时不考虑）

**Comment by bc-li** [comment]
added in #32.
