### ISSUE TITLE
ch02 部署wordpress后显示database error

### ISSUE THREAD

**Issue by scatyf3** [ustclug/Linux101-docs#43]
<img width="937" alt="image" src="https://github.com/ustclug/Linux101-docs/assets/96040102/fd7d80df-8c33-4949-81ab-ab6958c314cd">

我的电脑是m2芯片的mac，于是按照第一章的mac安装虚拟机教程，安装了VMWare Fusion，又安装了ubuntu 20.04.6 LTS。随后我自行上网安装了Xfce和firefox浏览器

然而在按照第二章教程本地部署wordpress时遇到了上图的报错，即Error establishing a database connection，我试图上网检索这个报错，但是这个报错对应的可能性错误太多了，作为刚接触linux，不了解前后端的小白比较难以一一排查，遂在这里提问。我的猜测是，我的虚拟机是否比官方给出的Xubuntu 的虚拟机镜像少安装了某几个软件，导致了这个错误？

（如果这个问题太蠢，请轻喷QAQ）

**Comment by taoky** [comment]
请看一下 `systemctl status mysql` 的输出。

**Comment by taoky** [comment]
由于已经有四个多月没有得到有效回复，此 issue 关闭。如有更多信息，仍然欢迎回复。
