### ISSUE TITLE
[勘误]Ch06中的位置变量

### ISSUE THREAD

**Issue by FeiNiaoBF** [ustclug/Linux101-docs#45]
[位置变量](https://101.lug.ustc.edu.cn/Ch06/#bash-positional-parameters)
![image](https://github.com/ustclug/Linux101-docs/assets/91862060/4796e4b6-774a-48eb-bec0-15df5258b749)

红框中应该是 `$ # 此时 $1 和 $2 已不存在`

**Comment by taoky** [comment]
```
$ set one two three
$ echo $1 $2 $3
one two three
$ shift 2
$ echo $1
three
$ echo $2

$ echo $3

$
```

**Comment by taoky** [comment]
所以这里没有错误。如果希望改进这个例子中的描述，可以考虑提交 PR。

**Comment by FeiNiaoBF** [comment]
哦哦，这样吗，谢谢你，我的问题
