### ISSUE TITLE
PDF下载

### ISSUE THREAD

**Issue by Cautreoxit** [ustclug/Linux101-docs#49]
您好，请问有没有办法将本书转化为本地的PDF？不太喜欢看网页，谢谢！

**Comment by taoky** [comment]
本书目前是为网页阅读而设计的，在电脑端与移动端都能有较好的使用体验。mkdocs 有一些第三方的 PDF 导出插件，但是我测试了 <https://github.com/jurgenwigg/mkpdfs2-mkdocs-plugin>，效果不太好：大部分 CSS 样式都丢失了，并且图片与代码均有超出页面的情况，如下图：

![image](https://github.com/ustclug/Linux101-docs/assets/2109893/eb04f003-9239-4ed5-b61e-4b6ea6db749a)
![image](https://github.com/ustclug/Linux101-docs/assets/2109893/c2b02bef-40ef-499f-a901-365014bd4ea6)
![image](https://github.com/ustclug/Linux101-docs/assets/2109893/7db71405-3de7-48cc-a556-447d29db16c6)

考虑到目前 PDF 导出的支持较差，并且所有能找到的插件均不处于积极的维护状态，目前没有提供 PDF 的考虑。如有需要，可本地自行尝试导出。
