### ISSUE TITLE
Ch08中，docker container ls 说明错误

### ISSUE THREAD

**Issue by Rokiers** [ustclug/Linux101-docs#53]
docker container ls 和docker ps 一样只能查看运行中的容器，并不能查看已经停止的容器

> 如果没有加上 --rm，退出后可以使用 docker ps -a 或者 docker container ls 查看系统中所有的容器。

这里应该给docker container ls 加上-a

**Comment by iBug** [comment]
感谢指出，`docker ps` 确实是 `docker container ls` 的一个 alias，功能上完全相同，我就把 `或者 docker container ls` 删掉了。
