### ISSUE TITLE
Ch01：“获取虚拟机管理软件” 部分的VMware Workstation Player链接貌似已经失效

### ISSUE THREAD

**Issue by overflowaker** [ustclug/Linux101-docs#60]
![Screenshot 2024-10-30 174700](https://github.com/user-attachments/assets/9e19e565-8f37-44d7-bafa-66d86f294482)
点击进入后显示 Page Not Found

**Comment by celeron533** [comment]
看来这个页面的内容要更新了

> VMware Workstation Pro: Now Available Free for Personal Use

https://blogs.vmware.com/workstation/2024/05/vmware-workstation-pro-now-available-free-for-personal-use.html

**Comment by celeron533** [comment]
VMWare被Broadcom收购后，下载 vmware workstation pro 还需要先注册账户（免费）

**Comment by celeron533** [comment]
来自tk教主的消息：

VMWare 在 2024 年 5 月宣布 VMware Workstation 对个人用户免费，2024 年 11 月又宣布对所有用户免费。

不过大家要注意：从当前的 17.6 版开始，VMware Workstation 不再支持物理并口、不再支持蓝牙设备。 ​​​
